server:
  port: 8080

spring:
  datasource:
    username: root
    password: dmr838714
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      generate-ddl: true
    #  show-sql: true
    open-in-view: true
  # logs
  logging:
      level:
        org.hibernate.SQL: info


indexing-settings:
  sites:
      - url: http://www.playback.ru
        name: PlayBack.Ru
      - url: https://nikoartgallery.com/
        name: Креативное пространство и галерея Н.Б. Никогосяна
